(global-set-key "\" "\\")
(global-set-key "\C-_" 'undo)
(global-set-key "\C-z" 'call-last-kbd-macro)
(global-set-key "\C-h" 'backward-delete-char-untabify)
(global-set-key "\M-h" 'backward-kill-word)
(global-set-key "\M-j" 'goto-line)
(global-set-key "\M-o" 'dabbrev-expand)
(global-set-key [(super ?o)] 'ispell-complete-word)
;(global-set-key "\M-@" 'lisp-complete-symbol)
(global-set-key "\C-xq" 'menu-bar-mode)
(define-key esc-map "&" 'query-replace-regexp)
(define-key global-map "\C-x\C-h" 'help-command)
(global-set-key "\C-xq" '(lambda ()
                           (interactive)
                           (setq truncate-lines (not truncate-lines)
                                 (recenter nil))))
(define-key minibuffer-local-completion-map "\C-w" 'backward-kill-word) ; ミニバッファ内C-wで単語削除
